from django.urls import include, path

from .media_views import stream_memory_media
from .views import (
    ChangeEmailView,
    ChangePasswordView,
    DeactivateAccountView,
    FamiliesView,
    FamilyDetailView,
    FamilyHouseholdsView,
    FamilyInviteView,
    FamilyInvitesView,
    FamilyMemberDetailView,
    FamilyMembersView,
    FamilyMessagesView,
    FamilyMomentsView,
    FamilyRelationshipLookupView,
    FamilySummaryView,
    FamilyTreeView,
    HouseholdDetailView,
    HouseholdDueRemindersView,
    HouseholdGroceriesView,
    HouseholdGroceryDetailView,
    HouseholdGroceryStatusView,
    HouseholdMembersView,
    HouseholdMessagesView,
    HouseholdReminderSnoozeView,
    JoinFamilyView,
    LoginView,
    LogoutView,
    MemoryDetailView,
    MyProfileView,
    RegisterView,
    RelationshipDetailView,
    RelationshipsView,
    RequestPasswordOtpView,
    ResendOtpView,
    RevokeOtherSessionsView,
    UserDetailView,
    UserSessionDetailView,
    UserSessionsView,
    UserSettingsView,
    VerifyOtpView,
)

urlpatterns = [
    # The Play section keeps its own URL module so games stay isolated from the rest.
    path("games/", include("apps.games.urls")),
    path("auth/register/", RegisterView.as_view()),
    path("auth/login/", LoginView.as_view()),
    path("auth/logout/", LogoutView.as_view()),
    path("auth/verify-otp/", VerifyOtpView.as_view()),
    path("auth/resend-otp/", ResendOtpView.as_view()),
    path("users/me/", MyProfileView.as_view()),
    path("users/me/settings/", UserSettingsView.as_view()),
    path("users/me/password/otp/", RequestPasswordOtpView.as_view()),
    path("users/me/password/", ChangePasswordView.as_view()),
    path("users/me/email/", ChangeEmailView.as_view()),
    path("users/me/deactivate/", DeactivateAccountView.as_view()),
    path("users/me/sessions/", UserSessionsView.as_view()),
    path("users/me/sessions/revoke-others/", RevokeOtherSessionsView.as_view()),
    path("users/me/sessions/<str:session_id>/", UserSessionDetailView.as_view()),
    path("users/<str:user_id>/", UserDetailView.as_view()),
    path("families/", FamiliesView.as_view()),
    path("families/join/", JoinFamilyView.as_view()),
    path("families/<str:family_id>/", FamilyDetailView.as_view()),
    path("families/<str:family_id>/members/", FamilyMembersView.as_view()),
    path("families/<str:family_id>/members/<str:user_id>/", FamilyMemberDetailView.as_view()),
    path("families/<str:family_id>/invite/", FamilyInviteView.as_view()),
    path("families/<str:family_id>/invites/", FamilyInvitesView.as_view()),
    path("families/<str:family_id>/messages/", FamilyMessagesView.as_view()),
    path("families/<str:family_id>/tree/", FamilyTreeView.as_view()),
    path("families/<str:family_id>/relationship/", FamilyRelationshipLookupView.as_view()),
    path("families/<str:family_id>/summary/", FamilySummaryView.as_view()),
    path("families/<str:family_id>/households/", FamilyHouseholdsView.as_view()),
    path("families/<str:family_id>/moments/", FamilyMomentsView.as_view()),
    path("families/<str:family_id>/moments/<str:memory_id>/", MemoryDetailView.as_view()),
    path("memories/media/<str:memory_id>/<str:file_id>/", stream_memory_media),
    path("households/<str:household_id>/", HouseholdDetailView.as_view()),
    path("households/<str:household_id>/members/", HouseholdMembersView.as_view()),
    path("households/<str:household_id>/messages/", HouseholdMessagesView.as_view()),
    path("households/<str:household_id>/groceries/", HouseholdGroceriesView.as_view()),
    path("households/<str:household_id>/groceries/<str:grocery_id>/", HouseholdGroceryDetailView.as_view()),
    path("households/<str:household_id>/groceries/<str:grocery_id>/status/", HouseholdGroceryStatusView.as_view()),
    path("households/<str:household_id>/reminders/due/", HouseholdDueRemindersView.as_view()),
    path("households/<str:household_id>/reminders/<str:reminder_id>/snooze/", HouseholdReminderSnoozeView.as_view()),
    path("relationships/", RelationshipsView.as_view()),
    path("relationships/<str:relationship_id>/", RelationshipDetailView.as_view()),
]
