from django.urls import path

from .views import (
    FamiliesView,
    FamilyDetailView,
    FamilyHouseholdsView,
    FamilyInviteView,
    FamilyMemberDetailView,
    FamilyMembersView,
    FamilyRelationshipLookupView,
    FamilySummaryView,
    FamilyTreeView,
    HouseholdDetailView,
    HouseholdDueRemindersView,
    HouseholdGroceriesView,
    HouseholdGroceryDetailView,
    HouseholdGroceryStatusView,
    HouseholdMembersView,
    HouseholdMessagesView,
    HouseholdReminderSnoozeView,
    JoinFamilyView,
    LoginView,
    LogoutView,
    MyProfileView,
    RegisterView,
    RelationshipDetailView,
    RelationshipsView,
    UserDetailView,
)

urlpatterns = [
    path("auth/register/", RegisterView.as_view()),
    path("auth/login/", LoginView.as_view()),
    path("auth/logout/", LogoutView.as_view()),
    path("users/me/", MyProfileView.as_view()),
    path("users/<str:user_id>/", UserDetailView.as_view()),
    path("families/", FamiliesView.as_view()),
    path("families/join/", JoinFamilyView.as_view()),
    path("families/<str:family_id>/", FamilyDetailView.as_view()),
    path("families/<str:family_id>/members/", FamilyMembersView.as_view()),
    path("families/<str:family_id>/members/<str:user_id>/", FamilyMemberDetailView.as_view()),
    path("families/<str:family_id>/invite/", FamilyInviteView.as_view()),
    path("families/<str:family_id>/tree/", FamilyTreeView.as_view()),
    path("families/<str:family_id>/relationship/", FamilyRelationshipLookupView.as_view()),
    path("families/<str:family_id>/summary/", FamilySummaryView.as_view()),
    path("families/<str:family_id>/households/", FamilyHouseholdsView.as_view()),
    path("households/<str:household_id>/", HouseholdDetailView.as_view()),
    path("households/<str:household_id>/members/", HouseholdMembersView.as_view()),
    path("households/<str:household_id>/messages/", HouseholdMessagesView.as_view()),
    path("households/<str:household_id>/groceries/", HouseholdGroceriesView.as_view()),
    path("households/<str:household_id>/groceries/<str:grocery_id>/", HouseholdGroceryDetailView.as_view()),
    path("households/<str:household_id>/groceries/<str:grocery_id>/status/", HouseholdGroceryStatusView.as_view()),
    path("households/<str:household_id>/reminders/due/", HouseholdDueRemindersView.as_view()),
    path("households/<str:household_id>/reminders/<str:reminder_id>/snooze/", HouseholdReminderSnoozeView.as_view()),
    path("relationships/", RelationshipsView.as_view()),
    path("relationships/<str:relationship_id>/", RelationshipDetailView.as_view()),
]
